library10/Models/ApplicationRole.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;

namespace library10.Models
{
    public class ApplicationRole : IdentityRole
    {
        public string Description { get; set; }
    }
}

library10/Models/ViewModels/ApplicationRoleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace library10.Models.ViewModels
{
    public class ApplicationRoleViewModel
    {
        public string Id { get; set; }

        [Display(Name = "عنوان نقش")]
        [Required(ErrorMessage = "لطفا عنوان نقش را وارد نمایید.")]
        public string Name { get; set; }

        [Display(Name ="توضیحات نقش" )]
        [Required(ErrorMessage = "لطفا توضیحات را وارد نمایید.")]
        public string Description { get; set; }

        public int NumberOfUsers { get; set; }

    }
}

library10/Areas/Admin/Controllers/ApplicationRoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using library10.Models;
using library10.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace library10.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ApplicationRoleController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<ApplicationRole> _roleManager;
        private readonly ApplicationDbContext _context;

        public ApplicationRoleController(UserManager<ApplicationUser> userManager, RoleManager<ApplicationRole> roleManager, ApplicationDbContext context)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var alluserRole = _context.UserRoles.ToList();
            List<ApplicationRoleViewModel> model = new List<ApplicationRoleViewModel>();
            model = _roleManager.Roles.Select(r => new ApplicationRoleViewModel
            {                
                NumberOfUsers = alluserRole.Count(ur=>ur.RoleId==r.Id),
                Id = r.Id,
                Name = r.Name,
                Description = r.Description
            }).ToList();


            return View(model);

        }

        [HttpGet]
        public async Task<IActionResult> AddEditRole(string id)
        {
            ApplicationRoleViewModel model = new ApplicationRoleViewModel();
            if (!string.IsNullOrEmpty(id)) //baraye virayesh
            {
                // peyda kardan naqsh
                ApplicationRole applicationRole = await _roleManager.FindByIdAsync(id);

                if (applicationRole != null) // agar id peydashod
                {
                    model.Id = applicationRole.Id;
                    model.Name = applicationRole.Name;
                    model.Description = applicationRole.Description;

                }
                else
                {
                    return RedirectToAction("Index");
                }

            }
            return PartialView("_AddEditApplicationRole", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddEditRole(string id, ApplicationRoleViewModel model, string redirecturl)
        {
            if (ModelState.IsValid)
            {
                bool isExist = !String.IsNullOrEmpty(id);
                ApplicationRole applicationrole = isExist
                    ? await _roleManager.FindByIdAsync(id)
                    : new ApplicationRole
                    {

                    };
                applicationrole.Name = model.Name;
                applicationrole.Description = model.Description;

                IdentityResult roleResult = isExist ? await _roleManager.UpdateAsync(applicationrole) :
               await _roleManager.CreateAsync(applicationrole);
                if (roleResult.Succeeded)
                {
                    return PartialView("_SuccessFullyResponse", redirecturl);
                }
            }
           
                return PartialView("_AddEditApplicationRole", model);

           
        }
        [HttpGet]
        public async Task<IActionResult> DeleteRole(string id)
        {
            // srring motaghayer
            string name = string.Empty;
            //string class
            if (!String.IsNullOrEmpty(id))
            {
                ApplicationRole ar = await _roleManager.FindByIdAsync(id);
                if (ar!=null)
                {
                    name = ar.Description;
                }
            }
            return PartialView("_DeleteRole", name);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteRole(string id, IFormCollection form)
        {
            if (!String.IsNullOrEmpty(id))
            {
                ApplicationRole ar = await _roleManager.FindByIdAsync(id);
                if (ar!=null)
                {
                    IdentityResult roleResult =  _roleManager.DeleteAsync(ar).Result;
                    if (roleResult.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            return View();
        }

    }
}

library10/Areas/Admin/Views/ApplicationRole/Index.cshtml
@using library10.PublicModel
@model IEnumerable<library10.Models.ViewModels.ApplicationRoleViewModel>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, library10
@using System.Data.SqlTypes

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    @Html.Partial("_AdminPanel")
</div>
<div class="col-md-9">
    <div class="topbuffer"></div>
    <div class="panel panel-primary">

        <div class="panel-heading panel-head">لیست نفش ها</div>

        <div class="panel-body">
            <div class="btn btn-group marginbootn">

                <a class="btn btn-primary" id="ShowAddRole" data-toggle="modal" asp-action="AddEditRole"
                   data-target="#modal-action-application-role">
                    <i class="glyphicon glyphicon-plus"></i>
                    افزودن نقش

                </a>

            </div>

            <div></div>
            <table class="table table-bordered table-striped table-condensed">

                <thead>
                    <tr>
                        <th>نام نقش</th>
                        <th>توضیحات</th>
                        <th>تعداد کاربر</th>
                        <th>عملیات</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                          
                            <td>@item.Name</td>
                            <td>@item.Description</td>
                           <td>@item.NumberOfUsers</td>
                            <td>
                                <a class="btn btn-info" id="ShowEditUser" asp-action="AddEditRole" asp-route-Id="@item.Id" data-toggle="modal"
                                   data-target="#modal-action-application-role">



                                    <i class="glyphicon glyphicon-pencil"></i>
                                    ویرایش نقش
                                </a>

                                @if (item.NumberOfUsers == 0)
                                {
                                    <a class="btn btn-danger" id="ShowDeleterole" asp-action="DeleteRole" asp-route-Id="@item.Id" data-toggle="modal"
                                       data-target="#modal-action-application-role">
                                        <i class="glyphicon glyphicon-trash"></i>
                                        حذف نقش
                                    </a>
                                }



                            </td>
                        </tr>
                    }



                </tbody>



            </table>



        </div>

    </div>
    </div>
    @Html.Partial("_Modal", new BootstrapModel { ID = "modal-action-application-role", Size = ModalSize.Medium })

    @section Scripts{

        <script src="~/js/ModalJs/application-role-index.js"></script>
        <script src="~/js/AdminPanelScript.js"></script>


    }

library10/Areas/Admin/Views/ApplicationRole/_AddEditApplicationRole.cshtml
@using library10.PublicModel
@model library10.Models.ViewModels.ApplicationRoleViewModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, library10


<form asp-action="AddEditRole" asp-controller="ApplicationRole"  id="addeditrole" data-ajax="true" data-ajax-method="POST"
      data-ajax-update="#addeditrole" data-ajax-mode="replace">
    
   @* Header *@
    @if (string.IsNullOrEmpty(Model.Id))
    {
        @await Html.PartialAsync("_ModalHeader", new ModalHeader {Heading = "افزودن نقش  سیستمی"})

    }

    else
    {
        @await Html.PartialAsync("_ModalHeader", new ModalHeader {Heading = "ویرایش نقش سیستمی"})

    }

    @* body *@
    <div class="modal-body form-horizontal">
        <div class="row">
            <div class="form-group">
                <label asp-for="Name" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Description" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>

                </div>
            </div>

            <div class="form-group hidden">
                <label asp-for="Id" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="Id" class="form-control" />

                </div>
            </div>
            <input type="hidden" name="redirecturl" value="@Url.Action("Index","ApplicationRole")"/>

        </div>


    </div>

    @* Footer *@
    @if (string.IsNullOrEmpty(Model.Id))
    {
        @await Html.PartialAsync("_ModalFooter",new ModalFooter{SubmitButtonText = "افزودن نقش"})

    }
    else
    {
        @await Html.PartialAsync("_ModalFooter",new ModalFooter{SubmitButtonText = "ویرایش نقش"})

    }

</form>

library10/Areas/Admin/Views/ApplicationRole/_DeleteRole.cshtml
@model string
@using library10.PublicModel


@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, library10

<form asp-controller="ApplicationRole" asp-action="DeleteRole">

    @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "حذف نقش" })

    <div class="modal-body form-horizontal">
        آیا از حذف نقش @Model مطمئن هستید؟
    </div>

    @await Html.PartialAsync("_ModalFooter", new ModalFooter { SubmitButtonText = "حذف نقش" })



</form>