library10/Areas/User/Controllers/UserProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using library10.Models;
using library10.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ReflectionIT.Mvc.Paging;

namespace library10.Areas.User.Controllers
{
    [Area("User")]
    [Authorize(Roles = "User")]

    public class UserProfileController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IServiceProvider _iServiceProvider;
        private readonly UserManager<ApplicationUser> _userManager;

        private readonly IHostingEnvironment _appEnvironment;

        public UserProfileController(ApplicationDbContext context, IServiceProvider iServiceProvider, UserManager<ApplicationUser> userManager, IHostingEnvironment appEnvironment)
        {
            _context = context;
            _iServiceProvider = iServiceProvider;
            _userManager = userManager;
            _appEnvironment = appEnvironment;
        }
        public async Task<IActionResult> Index(int page=1)
        {

          //  List<ManageRequestViewModel> model = new List<ManageRequestViewModel>();
          var model = (from br in _context.BorrowBooks
                join b in _context.Books on br.BookId equals b.BookId
                join u in _context.Users on br.UserId equals u.Id
                //برای اینکه کتاب های مربوط به کاربری که لاگین کرده رو بیاره نه همه کتاب ها
                //با این شرط ای دی کاربری که لاگین کرده را میگریم ومقایسه میکنیم
                where u.Id == _userManager.GetUserId(HttpContext.User)
                select new ManageRequestViewModel
                {
                    Id = br.Id,
                    BookId = br.BookId,
                    UserId = br.UserId,
                    UserFullName = u.FirstName + " " + u.LastName,
                    BookStock = b.BookStock,
                    BookName = b.BookName,
                    Flag = br.Flag,
                    RequestDate = br.RequestDate,
                    AnswerDate = br.AnswerDate,
                    Price = br.Price,
                    BackDate = br.BackDate,
                    FlagDescription = (
                        br.Flag == 1 ? "درخواست امانت" :
                        br.Flag == 2 ? "به امانت برده" :
                        br.Flag == 3 ? "رد درخواست" :
                        br.Flag == 4 ? "برگردانده" : "نامشخص"
                    )
                }).AsNoTracking().OrderBy(r=>r.Id);
          var modelpaging = await PagingList<ManageRequestViewModel>.CreateAsync(model, 10, page);
            var querfullname = (from u in _context.Users where u.Id == _userManager.GetUserId(HttpContext.User) select u).SingleOrDefault();
            ViewBag.kifepool = querfullname.KifePool;
            ViewBag.FullName =querfullname.FirstName + " " + querfullname.LastName;
            return View(modelpaging);
        }
        public async Task<IActionResult> SearchInRequests(string fromDate1,string todate1,string bookSearch,int page=1)
        {
            //  List<ManageRequestViewModel> model = new List<ManageRequestViewModel>();
            var model = (from br in _context.BorrowBooks
                join b in _context.Books on br.BookId equals b.BookId
                join u in _context.Users on br.UserId equals u.Id
                //برای اینکه کتاب های مربوط به کاربری که لاگین کرده رو بیاره نه همه کتاب ها
                //با این شرط ای دی کاربری که لاگین کرده را میگریم ومقایسه میکنیم
                where u.Id == _userManager.GetUserId(HttpContext.User)
                select new ManageRequestViewModel
                {
                    Id = br.Id,
                    BookId = br.BookId,
                    UserId = br.UserId,
                    UserFullName = u.FirstName + " " + u.LastName,
                    BookStock = b.BookStock,
                    BookName = b.BookName,
                    Flag = br.Flag,
                    Price = br.Price,
                    RequestDate = br.RequestDate,
                    AnswerDate = br.AnswerDate,
                    BackDate = br.BackDate,
                    FlagDescription = (
                        br.Flag == 1 ? "درخواست امانت" :
                        br.Flag == 2 ? "به امانت برده" :
                        br.Flag == 3 ? "رد درخواست" :
                        br.Flag == 4 ? "برگردانده" : "نامشخص"
                    )
                }).AsNoTracking().OrderBy(r => r.Id);
            var modelpaging = await PagingList<ManageRequestViewModel>.CreateAsync(model, 10, page);


            if (bookSearch != null)
            {
                modelpaging = await PagingList<ManageRequestViewModel>.CreateAsync(
                    model.Where(
                        r => r.BookName.Contains(bookSearch)).OrderBy(r => r.Id), 10, page);
            }
            if (fromDate1 != null)
            {
                //ازتاریخ فرام دیت یک به بعد
                modelpaging = await PagingList<ManageRequestViewModel>.CreateAsync(model.Where(
                    t => t.RequestDate.CompareTo(fromDate1) >= 0).OrderBy(t => t.Id), 10, page);
            }

            if (todate1 != null)
            {
                //ازتاریخ تودیت یک به قبل
                modelpaging = await PagingList<ManageRequestViewModel>.CreateAsync(model.Where(
                    t => t.RequestDate.CompareTo(todate1) <= 0).OrderBy(t => t.Id), 10, page);
            }
            var querfullname = (from u in _context.Users where u.Id == _userManager.GetUserId(HttpContext.User) select u).SingleOrDefault();

            ViewBag.FullName = querfullname.FirstName + " " + querfullname.LastName;
            ViewBag.kifepool = querfullname.KifePool;
            return View("Index", modelpaging);
        }
        [HttpGet]
        public IActionResult ChangeUserPass()
        {
            var querfullname = (from u in _context.Users where u.Id == _userManager.GetUserId(HttpContext.User) select u).SingleOrDefault();
            ViewBag.kifepool = querfullname.KifePool;
            ViewBag.FullName = querfullname.FirstName + " " + querfullname.LastName;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ChangeUserPass(ChangeUserPassViewMole model)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser user = new ApplicationUser();
                user = (from u in _context.Users where u.Id == _userManager.GetUserId(HttpContext.User) select u).SingleOrDefault();
                if (await _userManager.CheckPasswordAsync(user,model.OldPassword))
                {
                    //correct oldpassword
                    await _userManager.ChangePasswordAsync(user,model.OldPassword,model.NewPassword);
                    ViewBag.changepass = "رمزعبور با موفقیت تغییر یافت.";
                    return View(model);
                }
                else
                {
                    //incorrect oldpassword
                    ModelState.AddModelError("OldPassword","رمزعبور قدیمی شما صحیح نمی باشد.");
                    return View(model);
                }
            }

            return View(model);
        }
    }
}

library10/Areas/User/Views/UserProfile/ChangeUserPass.cshtml
@model library10.Models.ViewModels.ChangeUserPassViewMole
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, library10
@using library10.PublicModel

@{
    ViewData["Title"] = "مدیریت درخواست های رسیده";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    @Html.Partial("_UserPanel")
</div>
<div class="col-md-9">
    <div class="topbuffer"></div>
    <div class="panel panel-primary">

        <div class="panel-heading panel-head">مدیریت درخواست ها </div>

        <div class="panel-body form-horizontal">
            <form asp-controller="UserProfile" asp-action="ChangeUserPass" method="post">
                @if (ViewBag.changepass != null)
                {
                    <span style="color: green; font-size: 18px;">@ViewBag.changepass</span>

                }

                <div class="form-group">
                    <label asp-for="OldPassword" class="col-lg-3 col-sm-3 control-label"></label>
                    <div class="col-lg-6">
                        <input asp-for="OldPassword" class="form-control" />
                        <span class="text-danger">@Html.ValidationMessage("OldPassword")</span>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="NewPassword" class="col-lg-3 col-sm-3 control-label"></label>
                    <div class="col-lg-6">
                        <input asp-for="NewPassword" class="form-control" />
                        <span asp-validation-for="NewPassword" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label asp-for="ConfirmNewPassword" class="col-lg-3 col-sm-3 control-label"></label>
                    <div class="col-lg-6">
                        <input asp-for="ConfirmNewPassword" class="form-control" />
                        <span asp-validation-for="ConfirmNewPassword" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-lg-6">
                        <input asp-for="Id" class="hidden" />
                    </div>
                </div>

                <div class="form-group" style="text-align: center">
                    <button type="submit" class="btn btn-success">تغییر رمزعبور</button>
                </div>
            </form>
        </div>

    </div>

</div>

@section Scripts{
    <script src="~/js/AdminPanelScript.js"></script>
}

library10/Areas/User/Views/UserProfile/Index.cshtml
@model ReflectionIT.Mvc.Paging.PagingList<library10.Models.ViewModels.ManageRequestViewModel>
@using ReflectionIT.Mvc.Paging
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, library10
@using library10.PublicModel

@{
    ViewData["Title"] = "مدیریت درخواست های رسیده";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/TimePicker/jquery.Bootstrap-PersianDateTimePicker.css" rel="stylesheet" />
<div>
    @Html.Partial("_UserPanel")
</div>
<div class="col-md-9">
    <div class="topbuffer"></div>
    <div class="panel panel-primary">


        <div class="panel-heading" style="border:0px; margin:0 !important; padding-bottom:1px;">
            <div class="col-md-3" style="font-size:17px;">مشاهده ی وضعیت درخواست ها  </div>

            <form method="post" asp-controller="UserProfile" asp-action="SearchInRequests" class="form-horizontal">
                <div class="form-group">
                    <div class="col-md-2">
                        <input type="text" id="bookSearch" name="bookSearch" class="form-control" placeholder="جستجو در نام کتابها.." />
                    </div>
                    <div class="input-group col-md-2 pull-right">
                        <div class="input-group-addon" data-MdDateTimePicker="true" data-trigger="click" data-targetselector="#fromDate1" data-groupid="group1" data-fromdate="true" data-enabletimepicker="false" data-placement="left">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </div>
                        <input type="text" class="form-control" id="fromDate1" name="fromDate1" placeholder="از تاریخ" data-MdDateTimePicker="true" data-trigger="click" data-targetselector="#fromDate1" data-groupid="group1" data-fromdate="true" data-enabletimepicker="false" data-placement="right" />
                    </div>

                    <div class="input-group col-md-2 pull-right">
                        <div class="input-group-addon" data-MdDateTimePicker="true" data-trigger="click" data-targetselector="#todate1">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </div>
                        <input type="text" class="form-control" id="todate1" name="todate1" placeholder="تا تاریخ" data-MdDateTimePicker="true" data-placement="right" />
                    </div>

                    <div class="btn-group col-md-2 pull-left">
                        <button class="btn btn-default pull-right" type="submit">جستجو</button>
                    </div>
                </div>
            </form>
        </div>


        <div class="panel-body">

            <table class="table table-bordered table-striped table-condensed">

                <thead>
                    <tr>
                        <th class="text-center" style="font-weight: 600">ردیف</th>
                        <th class="text-center">@Html.DisplayNameFor(model => model.BookName) </th>
                        <th class="text-center">@Html.DisplayNameFor(model => model.FlagDescription) </th>
                        <th class="text-center">@Html.DisplayNameFor(model => model.Price) </th>
                        <th class="text-center">@Html.DisplayNameFor(model => model.RequestDate) </th>
                        <th class="text-center">@Html.DisplayNameFor(model => model.AnswerDate) </th>
                        <th class="text-center">@Html.DisplayNameFor(model => model.BackDate) </th>

                    </tr>
                </thead>
                <tbody>
                    @{
                        int counter = 1;

                        foreach (var item in Model)
                        {
                            <tr style="height: 50px">
                                <td class="text-center">@(counter++)</td>
                                <td class="text-center" style="color: rgb(128, 0, 64); background-color: rgb(128, 116, 10)">@item.BookName</td>

                                @if (item.Flag == 1)
                                {
                                    <td class="text-center" style="color: red; background-color: pink">@item.FlagDescription</td>

                                }
                                @if (item.Flag == 2)
                                {
                                    <td class="text-center" style="color: brown; background-color: lightgoldenrodyellow">@item.FlagDescription</td>

                                }
                                @if (item.Flag == 3)
                                {
                                    <td class="text-center" style="color: thistle; background-color: lightcoral">@item.FlagDescription</td>

                                }
                                @if (item.Flag == 4)
                                {
                                    <td class="text-center" style="color: sienna; background-color: aqua">@item.FlagDescription</td>

                                }

                                <td class="text-center" style="color: blue; background-color: orangered">@item.Price</td>

                                <td class="text-center" style="color: blue; background-color: yellowgreen">@item.RequestDate</td>
                                <td class="text-center" style="color: brown; background-color: lightgoldenrodyellow">@item.AnswerDate</td>
                                <td class="text-center" style="color: yellow; background-color: rgb(6, 134, 196)">@item.BackDate</td>

                            </tr>
                        }
                    }

                </tbody>

            </table>
            <nav class="text-center">@await this.Component.InvokeAsync("Pager",new{PagingList=this.Model })</nav>
        </div>

    </div>

</div>

@section Scripts{
    <script src="~/js/AdminPanelScript.js"></script>
    <script src="~/TimePicker/calendar.js"></script>
    <script src="~/TimePicker/jquery.Bootstrap-PersianDateTimePicker.js"></script>
}