library10/Models/News.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace library10.Models
{
    public class News
    {
        [Key]
        public int NewsId { get; set; }


        [Display(Name = "عنوان اطلاعیه")]
        [Required(ErrorMessage = "لطفا عنوان اطلاعیه را وارد نمایید.")]
        public string NewsTitle { get; set; }


        [Display(Name = "متن اطلاعیه")]
        [Required(ErrorMessage = "لطفا متن اطلاعیه را وارد نمایید.")]
        public string NewsContent { get; set; }


        [Display(Name = "تاریخ اطلاعیه")]
        public string NewsDate { get; set; }


        [Display(Name = "تصویر اطلاعیه")]
        public string NewsImage { get; set; }
        
    }
}

library10/Areas/Admin/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using library10.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using ReflectionIT.Mvc.Paging;

namespace library10.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]

    public class NewsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IServiceProvider _iServiceProvider;
        private readonly IHostingEnvironment _appEnvironment;

        public NewsController(ApplicationDbContext context, IServiceProvider iServiceProvider,
            IHostingEnvironment appEnvironment)
        {
            _context = context;
            _iServiceProvider = iServiceProvider;
            _appEnvironment = appEnvironment;
        }

        public async Task<IActionResult> Index(int page=1)
        {
            //List<News> model = new List<News>();
          var  model = _context.news.AsNoTracking().Select(n => new News
            {
                NewsId = n.NewsId,
                NewsTitle = n.NewsTitle,
                NewsDate = n.NewsDate,
                NewsImage = n.NewsImage
            }).OrderBy(n=>n.NewsId);
          var modelpaging = await PagingList<News>.CreateAsync(model, 10, page);
            ViewBag.Rootpath = "/upload/normalImage/";
            return View(modelpaging);
        }
        public async Task<IActionResult> SearchInNews(string fromDate1, string todate1, string newsSearch,int page=1)
        {
            //List<News> model = new List<News>();
            var model = _context.news.AsNoTracking().Select(n => new News
            {
                NewsId = n.NewsId,
                NewsTitle = n.NewsTitle,
                NewsDate = n.NewsDate,
                NewsImage = n.NewsImage
            }).OrderBy(n => n.NewsId);
            var modelpaging = await PagingList<News>.CreateAsync(model, 10, page);
          
            if (newsSearch!=null)
            {
                modelpaging =
                    await PagingList<News>.CreateAsync(
                        model.Where(n => n.NewsTitle.Contains(newsSearch)).OrderBy(n => n.NewsId), 10, page);
            }
            if (fromDate1 != null && todate1==null)
            {
                //ازتاریخ فرام دیت یک به بعد
                modelpaging =
                    await PagingList<News>.CreateAsync(model.Where(t=>t.NewsDate.CompareTo(fromDate1)>=0).OrderBy(n=>n.NewsId),10,page);
            }

            if (todate1!=null && fromDate1==null)
            {
                //ازتاریخ تودیت یک به قبل
                modelpaging =
                    await PagingList<News>.CreateAsync(model.Where(t => t.NewsDate.CompareTo(todate1) <= 0).OrderBy(n => n.NewsId), 10, page);
            }

            if (todate1 != null && fromDate1 != null)
            {
                modelpaging =
                    await PagingList<News>.CreateAsync(model.Where(t => t.NewsDate.CompareTo(todate1) <= 0 && t.NewsDate.CompareTo(todate1) <= 0).OrderBy(n => n.NewsId), 10, page);

            }
            ViewBag.Rootpath = "/upload/normalImage/";
            return View("Index", modelpaging);
        }
        [HttpGet]
        public IActionResult AddEditNews(int id)
        {
            var model = new News();
            if (id != 0)
            {
                //update
                using (var db = _iServiceProvider.GetRequiredService<ApplicationDbContext>())
                {

                    model = _context.news.Where(n => n.NewsId == id).SingleOrDefault();
                    if (model == null)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            //بدست اوردن تاریخ شمسی
            var currentDay = DateTime.Now;
            PersianCalendar pcalender = new PersianCalendar();
            int year = pcalender.GetYear(currentDay);
            int month = pcalender.GetMonth(currentDay);
            int day = pcalender.GetDayOfMonth(currentDay);


            string ShamsiDate = string.Format("{0:yyyy/MM/dd}", Convert.ToDateTime(year + "/" + month + "/" + day));

            ViewBag.sdate = ShamsiDate;

            return PartialView("_AddEditNews", model);

        }

        [HttpPost]
        // [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddEditNews(News model, int NewsId, IEnumerable<IFormFile> files,
            string ImageName)
        {

            if (ModelState.IsValid)
            {
                ///upload iamge//////
                var uploads = Path.Combine(_appEnvironment.WebRootPath, "upload\\normalImage\\");
                foreach (var file in files)
                {
                    if (file != null && file.Length > 0)
                    {
                        var filename = Guid.NewGuid().ToString().Replace("-", "") + Path.GetExtension(file.FileName);

                        using (var filestream = new FileStream(Path.Combine(uploads, filename), FileMode.Create))
                        {
                            await file.CopyToAsync(filestream);
                            model.NewsImage = filename;
                        }
                        /////ایجاد تصاویر بند انگشتی یا تصاویر کوچک ///ایجاد تصاویر بند انگشتی یا تصاویر کوچک
                        //InsertShowImage.ImageResizer img = new InsertShowImage.ImageResizer();
                        //img.Resize(uploads + filename, _appEnvironment.WebRootPath + "\\upload\\thumbnailImage\\" + filename);
                    }
                }
                ///upload image///

                if (NewsId == 0)
                {
                    if (model.NewsImage == null)
                    {
                        // اگر تصویر انتخاب نشده بود.
                        model.NewsImage = "notidefault.jpg";
                    }
                    //afzodan
                    using (var db = _iServiceProvider.GetRequiredService<ApplicationDbContext>())
                    {
                        // Book bookmodel = AutoMapper.Mapper.Map<AddEditBookViewModel, Book>(model);

                        db.news.Add(model);
                        db.SaveChanges();
                    }
                    return Json(new { status = "success", message = "اطلاعیه با موفقیت ایجاد شد." });
                }
                else
                {
                    // virayesh
                    using (var db = _iServiceProvider.GetRequiredService<ApplicationDbContext>())
                    {
                        if (model.NewsImage == null)
                        {
                            //در حالت ویرایش اگر تصویر خالی بود با ای میج نیم که با استرینگ ارسال شده بود را جایگزین میکنیم
                            model.NewsImage = ImageName;
                        }
                        //  Book bookmodel = AutoMapper.Mapper.Map<AddEditBookViewModel, Book>(model);

                        db.news.Update(model);
                        db.SaveChanges();
                    }
                    return Json(new { status = "success", message = "اطلاعیه با موفقیت ویرایش شد." });

                }
            }

            //نشان دادن ولیدیشن ها با جی کوئری ایجکس

            var list = new List<string>();

            foreach (var validation in ViewData.ModelState.Values)
            {
                list.AddRange(validation.Errors.Select(error => error.ErrorMessage));
            }

            return Json(new { status = "error", error = list });

        }




        [HttpGet]
        public async Task<IActionResult> DeleteNews(int id)
        {
            var model = new News();
            using (var db = _iServiceProvider.GetRequiredService<ApplicationDbContext>())
            {
                model = db.news.Where(b => b.NewsId == id).SingleOrDefault();
                if (model == null)
                {
                    return RedirectToAction("Index");
                }

            }
            return PartialView("_DeleteNews", model.NewsTitle);

        }

        [HttpPost]
        public async Task<IActionResult> DeleteNews(int id, IFormCollection form)
        {
            using (var db = _iServiceProvider.GetRequiredService<ApplicationDbContext>())
            {
                var model = _context.news.Where(b => b.NewsId == id).SingleOrDefault();

                //چون بعد از حذف عکس ها در پوشه ها داخل نرم افزار میماند میتوانیم به صورت دستی در محل ذخیره پروژه عکس ها را حف کنیم وبرنامه را باز و بسته کنیم 
                //برای حذف عکس از روت سایت به صورت خودکار


                if (model.NewsImage != "notidefault.jpg")
                {
                    //برای جلو گیری از حذف تصویر پیش فرض درصورت نداشتن عکس


                    ////////////normalimage/////////////
                    var pathnormal = Path.Combine(_appEnvironment.WebRootPath, "upload\\normalImage\\") +
                                     model.NewsImage;
                    if (System.IO.File.Exists(pathnormal))
                    {
                        System.IO.File.Delete(pathnormal);
                    }
                    ////////////////thumbnailimage////////////

                    //var paththumbnail = Path.Combine(_appEnvironment.WebRootPath, "upload\\thumbnailImage\\") + model.BookImage;
                    //if (System.IO.File.Exists(paththumbnail))
                    //{
                    //    System.IO.File.Delete(paththumbnail);
                    //} 
                }

                db.news.Remove(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

        }

        [HttpGet]
        [AllowAnonymous]

library10/Areas/Admin/Views/News/Index.cshtml
@model ReflectionIT.Mvc.Paging.PagingList<library10.Models.News>
@using ReflectionIT.Mvc.Paging
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, library10
@using library10.PublicModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/TimePicker/jquery.Bootstrap-PersianDateTimePicker.css" rel="stylesheet" />
<div>
    @Html.Partial("_AdminPanel")
</div>
<div class="col-md-9">
    <div class="topbuffer"></div>
    <div class="panel panel-primary">

        
        @* https://www.codeproject.com/Articles/858123/Bootstrap-Persian-DateTimePicker *@
        <div class="panel-heading" style="border:0px; margin:0 !important; padding-bottom:1px;">
            <div class="col-md-3" style="font-size:17px;">لیست اخبار و اطلاعیه ها</div>
            
            <form method="post" asp-controller="News" asp-action="SearchInNews" class="form-horizontal">
                <div class="form-group">
                    <div class="col-md-2">
                        <input type="text" id="newsSearch" name="newsSearch" class="form-control" placeholder="جستجو دراخبار.." />
                    </div>
                    <div class="input-group col-md-2 pull-right">
                        <div class="input-group-addon" data-MdDateTimePicker="true" data-trigger="click" data-targetselector="#fromDate1" data-groupid="group1" data-fromdate="true" data-enabletimepicker="false" data-placement="left">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </div>
                        <input type="text" class="form-control" id="fromDate1" name="fromDate1" placeholder="از تاریخ" data-MdDateTimePicker="true" data-trigger="click" data-targetselector="#fromDate1" data-groupid="group1" data-fromdate="true" data-enabletimepicker="false" data-placement="right"/>
                    </div>

                    <div class="input-group col-md-2 pull-right">
                        <div class="input-group-addon" data-MdDateTimePicker="true" data-trigger="click" data-targetselector="#todate1">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </div>
                        <input type="text" class="form-control" id="todate1" name="todate1" placeholder="تا تاریخ" data-MdDateTimePicker="true" data-placement="right"/>
                    </div>


                    <div class="btn-group col-md-2 pull-left">
                        <button class="btn btn-default pull-right" type="submit">جستجو</button>
                    </div>
                </div>
            </form>
        </div>
        
        <div class="panel-body">
            <div class="btn btn-group marginbootn ">



                <a class="btn btn-primary" id="ShoweNews" data-toggle="modal" asp-action="AddEditNews"
                   data-target="#modal-action-news">
                    <i class="glyphicon glyphicon-plus"></i>
                    افزودن اطلاعیه جدید

                </a>

            </div>

            <div></div>
            <table class="table table-bordered table-striped table-condensed">

                <thead>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.NewsTitle) </th>
                        <th>@Html.DisplayNameFor(model => model.NewsDate) </th>
                        <th>@Html.DisplayNameFor(model => model.NewsImage) </th>

                        <th>عملیات</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.NewsTitle</td>
                            <td>@item.NewsDate</td>
                            <td class="text-center">

                                <img src="@ViewBag.Rootpath@item.NewsImage" style="width: 80px; height: 80px;" @*class="thumbnail" *@>
                            </td>

                            <td>

                                <a class="btn btn-info" id="ShowNews" asp-action="AddEditNews" asp-route-Id="@item.NewsId" data-toggle="modal"
                                   data-target="#modal-action-news">
                                    <i class="glyphicon glyphicon-pencil"></i>
                                    ویرایش اطلاعیه
                                </a>


                                <a class="btn btn-danger" id="ShowDeleteNews" asp-action="DeleteNews" asp-route-Id="@item.NewsId" data-toggle="modal"
                                   data-target="#modal-action-news">
                                    <i class="glyphicon glyphicon-trash"></i>
                                    حذف اطلاعیه
                                </a>

                            </td>
                        </tr>
                    }

                </tbody>

            </table>
            <nav class="text-center">@await this.Component.InvokeAsync("Pager",new {PagingList=this.Model })</nav>
        </div>

    </div>

</div>


@Html.Partial("_Modal", new BootstrapModel { ID = "modal-action-news", Size = ModalSize.Large })

@section Scripts{
    <script src="~/js/ModalJs/News-index.js"></script>
    <script src="~/js/AdminPanelScript.js"></script>
    <script src="~/js/ckeditor/ckeditor.js"></script>
    <script src="~/TimePicker/calendar.js"></script>
    <script src="~/TimePicker/jquery.Bootstrap-PersianDateTimePicker.js"></script>
    <script>
        $(document).on('click',
            '#submitdata',
            function(evt) {

                evt.preventDefault();


                var data = new FormData();

                //دریافت مقادیر فایل آپلودی
                var fileupload = $("#files").get(0);
                var files = fileupload.files;

                for (var i = 0; i < files.length; i++) {
                    data.append('files', files[i]);
                }

                //دریافت مقادیر موجود
                $('input').each(function(x,y) {

                    data.append($(y).attr('name'), $(y).val());

                });


                //دریافت مقادیر ادیتور

                var editorval = CKEDITOR.instances['NewsContent'].getData();

                data.append('NewsContent', editorval);

                ////ارسال به سمت سرور با ایجکس

                $.ajax({
                    type: "post",
                    url: '@Url.Action("AddEditNews","News",new{area ="Admin"})',
                    contentType: false,
                    processData: false,
                    data: data

                }).done(function(res) {
                    //منظور از دون  وقتی اطلاعات به سمت سرور رفت و جواب از سرور آمد
                    if (res.status === "success") {
                        alert(res.message);

                        window.location.href = '@Url.Action("Index","News")';
                    } else {

                        $.each(res.error, function(a, b) {
                            alert(b);
                        });

                    }
                }).fail(function(xhr, b, error) {
                    //منظور از فیل وقتی اطلاعات به سمت سرور نرفت و در همان کامپیوتر کلاینت یا در بدو ورود به سرور خطاداد

                    alert(error);

                });


            });

    </script>
}

library10/Areas/Admin/Views/News/NewsDetails.cshtml
@model library10.Models.News

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, library10



@{
    ViewData["Title"] = "NewsDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="newsdetails" class="container">
    <h3 id="newsheader" class="panel panel-primary panel-heading text-center">آخرین اخبار و اطلاعیه ها</h3>
    <div class="dl-horizontal">
        
        <div class="col-md-2" style="font-size: 17px">
            @Html.DisplayNameFor(model => model.NewsTitle)
        </div>
        <div class="col-md-10" style="font-size:16px">
            @Html.DisplayFor(model => model.NewsTitle)
        </div>
        
    </div>
    <br />
    <hr style="background-color: black;height:1px" />
    <div class="dl-horizontal">
        
        <div class="col-md-2" style="font-size: 17px">
            @Html.DisplayNameFor(model => model.NewsContent)
        </div>
        <div class="col-md-10" style="font-size:16px">
            @Html.Raw(Model.NewsContent)
        </div>
        
    </div>
    <br />
    <div class="dl-horizontal">
        
        <div class="col-md-2" style="font-size: 17px">
            @Html.DisplayNameFor(model => model.NewsDate)
        </div>
        <div class="col-md-10" style="font-size: 16px;color:blue">
            @Html.DisplayFor(model => model.NewsDate)
        </div>
        
    </div>

</div>

library10/Areas/Admin/Views/News/_AddEditNews.cshtml
@model library10.Models.News
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, library10
@using library10.PublicModel


<form method="post" enctype="multipart/form-data">

    @* Header *@
    @if (Model.NewsId == 0)

    {
        @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "افزودن اطلاعیه" })

}

    else
    {
        @await  Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "ویرایش اطلاعیه" })

}
    @Html.AntiForgeryToken();

    @* body *@
    <div class="modal-body form-horizontal">
        <div class="row">
            <div class="form-group">
                <label asp-for="NewsTitle" class="col-lg-2 col-sm-2 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="NewsTitle" class="form-control" />
                </div>
            </div>

            <div class="form-group">
                <label asp-for="NewsContent" class="col-lg-2 col-sm-2 control-label"></label>
                <div class="col-lg-9">
                    <textarea asp-for="NewsContent" class="form-control" id="NewsContent" name="NewsContent"></textarea>

                </div>

                <script type="text/javascript">
                    CKEDITOR.replace('NewsContent');

                </script>
            </div>


            <div class="form-group">
                <label asp-for="NewsImage" class="col-lg-2 col-sm-2 control-label"></label>
                <div class="col-lg-6">
                    <input type="file" id="files" name="files" multiple />
                </div>
                @if (Model.NewsId != 0)
                {
                    <input type="hidden" name="ImageName" value="@Model.NewsImage" />
                }
            </div>


            <div class="form-group">
                <label asp-for="NewsDate" class="col-lg-2 col-sm-2 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="NewsDate" value="@ViewBag.sdate" />
                </div>
            </div>
            

            <div class="form-group hidden">
                <label asp-for="NewsId" class="col-lg-2 col-sm-2 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="NewsId" class="form-control" />
                </div>
            </div>


            
            @*<input type="hidden" name="redirecturl" value="@Url.Action("Index","Book")" />*@
            @*بخاطر استفاده از جی کوئری برای ارسال فرم دیگر نیازی به این دستور نیست  *@
        </div>


    </div>

    @* Footer *@
    @if (Model.NewsId == 0)
    {

        @*@await Html.PartialAsync("_ModalFooter", new ModalFooter { SubmitButtonText = "افزودن کتاب" })*@
        <div class="modal-footer">
            <button class="btn btn-default" type="button" data-dismiss="modal">برگشت</button>

            <input type="button" id="submitdata" class="btn btn-success" value="افزودن اطلاعیه" />

        </div>
    }
    else
    {
        <div class="modal-footer">
            <button class="btn btn-default" type="button" data-dismiss="modal">برگشت</button>

            <input type="button" id="submitdata" class="btn btn-info" value="ویرایش اطلاعیه" />
        </div>
    }

</form>

library10/Areas/Admin/Views/News/_DeleteNews.cshtml
@model string
@using library10.PublicModel


@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, library10

<form asp-controller="News" asp-action="DeleteNews">

    @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "حذف اطلاعیه" })

    <div class="modal-body form-horizontal">
        آیا از حذف اطلاعیه @Model مطمئن هستید؟

    </div>

    @await Html.PartialAsync("_ModalFooter", new ModalFooter { SubmitButtonText = "حذف اطلاعیه" })

</form>