library10/Models/Book.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace library10.Models
{
    public class Book
    {
        //modele ketabha
        [Key]
        public int BookId { get; set; }

        public string BookName { get; set; }

        public string BookDescription { get; set; }

        public int BookPageCount { get; set; }

        public string BookImage { get; set; }

        public int BookStock { get; set; }

        public int Price { get; set; }

        public int BookViews { get; set; }

        public int BookLikeCount { get; set; }

        /////kelid khareji

        public int AuthorID { get; set; }
        [ForeignKey("AuthorID")]
        public virtual Author Authors { get; set; }



        public int BookgroupID { get; set; }
        [ForeignKey("BookgroupID")]
        public virtual BookGroup BookGroups { get; set; }

    }
}

library10/Models/ViewModels/AddEditBookViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace library10.Models.ViewModels
{
    public class AddEditBookViewModel
    {
        [Key]
        public int BookId { get; set; }


        [Display(Name = "نام کتاب:")]
        [Required(ErrorMessage = "لطفا نام کتاب را وارد نمایید. ")]
        public string BookName { get; set; }
        

        [Display(Name = "توضیحات:")]
        [Required(ErrorMessage = "لطفا توضیحات را وارد نمایید. ")]
        public string BookDescription { get; set; }

        [Display(Name = "تعداد صفحات:")]
        public int BookPageCount { get; set; }

        [Display(Name = "مبلغ امانت")]
        [Required(ErrorMessage = "لطفا مبلغ امانت را وارد نمایید.")]
        public int Price { get; set; }

        [Display(Name = "تصویر کتاب:")]
       // [Required(ErrorMessage = "لطفا تصویر کتاب را وارد نمایید. ")]
        public string BookImage { get; set; }

        ////////dropdown list dar inja kelide khareji  nadarim vabe onvane drop down list estefade kardim
        [Display(Name = "گروه بندی:")]
        public int BookGroupId { get; set; }

        public List<SelectListItem> BookGroups { get; set; }

        [Display(Name = "نام نویسنده:")]
        public int AuthorId { get; set; }

        public List<SelectListItem> Authors { get; set; }


    }
}

library10/Models/ViewModels/BookDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace library10.Models.ViewModels
{
    public class BookDetailsViewModel
    {

        public int BookId { get; set; }

        [Display(Name = "نام کتاب")]
        public string BookName { get; set; }

        [Display(Name = "توضیحات کتاب")]
        public string BookDescription { get; set; }

        [Display(Name = "تعداد صفحات")]
        public int BookPageCount { get; set; }

        [Display(Name = "تصویر کتاب")]
        public string BookImage { get; set; }

        [Display(Name = "موجودی")]
        public int BookStock { get; set; }

        [Display(Name = "مبلغ امانت")]
        public int Price { get; set; }


        [Display(Name = "تعداد بازدید کتاب")]
        public int BookViews { get; set; }

        public int BookLikeCount { get; set; }

        public int AuthorId { get; set; }

        public int BookGroupId { get; set; }

        [Display(Name = "نام نویسنده")]
        public string AuthorName { get; set; }

        [Display(Name = "نام گروه بندی")]
        public string BookGroupName { get; set; }
    }
}

library10/Areas/Admin/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using library10.Models;
using library10.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Newtonsoft.Json.Linq;
using ReflectionIT.Mvc.Paging;

namespace library10.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]

    public class BookController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IServiceProvider _iServiceProvider;
        private readonly UserManager<ApplicationUser> _userManager;

        private readonly IHostingEnvironment _appEnvironment;

        public BookController(ApplicationDbContext context, IServiceProvider iServiceProvider, UserManager<ApplicationUser> userManager, IHostingEnvironment appEnvironment)
        {
            _context = context;
            _iServiceProvider = iServiceProvider;
            _userManager = userManager;
            _appEnvironment = appEnvironment;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int page = 1)
        {
            //List<BookListViewModel> model = new List<BookListViewModel>();
            //linq to query string

            var query = (from b in _context.Books

                         join a in _context.Authors on b.AuthorID equals a.AuthorId
                         join bg in _context.BookGroups on b.BookgroupID equals bg.BookGroupId

                         select new BookListViewModel()
                         {
                             BookId = b.BookId,
                             BookName = b.BookName,
                             BookPageCount = b.BookPageCount,
                             BookImage = b.BookImage,
                             AuthorId = b.AuthorID,
                             BookGroupId = b.BookgroupID,
                             AuthorName = a.AuthorName,
                             BookGroupName = bg.BookGroupName,
                             Price = b.Price
                         }).AsNoTracking().OrderBy(b => b.BookId);
            //foreach (var item in query)
            //{
            //    BookListViewModel objmodel = new BookListViewModel();

            //    objmodel.BookId = item.BookId;
            //    objmodel.BookName = item.BookName;
            //    objmodel.BookImage = item.BookImage;
            //    objmodel.BookPageCount = item.BookPageCount;
            //    objmodel.AuthorId = item.AuthorID;
            //    objmodel.BookGroupId = item.BookgroupID;
            //    objmodel.AuthorName = item.AuthorName;
            //    objmodel.BookGroupName = item.BookGroupName;

            //    model.Add(objmodel);

            //}
            var modelpaging = await PagingList<BookListViewModel>.CreateAsync(query, 10, page);
            ViewBag.Rootpath = "/upload/thumbnailImage/";
            return View(modelpaging);
        }

        public async Task<IActionResult> SearchBook(string bookSearch, string authorSearch, string bookgroupSearch, int page = 1)
        {

            var query = (from b in _context.Books

                         join a in _context.Authors on b.AuthorID equals a.AuthorId
                         join bg in _context.BookGroups on b.BookgroupID equals bg.BookGroupId

                         select new BookListViewModel()
                         {
                             BookId = b.BookId,
                             BookName = b.BookName,
                             BookPageCount = b.BookPageCount,
                             BookImage = b.BookImage,
                             AuthorId = b.AuthorID,
                             BookGroupId = b.BookgroupID,
                             AuthorName = a.AuthorName,
                             Price = b.Price,
                             BookGroupName = bg.BookGroupName
                         }).AsNoTracking().OrderBy(b => b.BookId);
            //foreach (var item in query)
            //{
            //    BookListViewModel objmodel = new BookListViewModel();
            //    objmodel.BookId = item.BookId;
            //    objmodel.BookName = item.BookName;
            //    objmodel.BookImage = item.BookImage;
            //    objmodel.BookPageCount = item.BookPageCount;
            //    objmodel.AuthorId = item.AuthorID;
            //    objmodel.BookGroupId = item.BookgroupID;
            //    objmodel.AuthorName = item.AuthorName;
            //    objmodel.BookGroupName = item.BookGroupName;
            //    model.Add(objmodel);
            //}
            var modelpaging = await PagingList<BookListViewModel>.CreateAsync(query, 10, page);

            if (bookSearch != null)
            {
                modelpaging = await PagingList<BookListViewModel>.CreateAsync(
                    query.Where(b => b.BookName.Contains(bookSearch)).OrderBy(b => b.BookId), 10, page);
            }
            if (bookgroupSearch != null)
            {
                modelpaging = await PagingList<BookListViewModel>.CreateAsync(
                    query.Where(bg => bg.BookGroupName.Contains(bookgroupSearch)).OrderBy(bg => bg.BookId), 10, page);
            }
            if (authorSearch != null)
            {
                modelpaging = await PagingList<BookListViewModel>.CreateAsync(
                    query.Where(a => a.AuthorName.Contains(authorSearch)).OrderBy(b => b.BookId), 10, page);
            }



            ViewBag.Rootpath = "/upload/thumbnailImage/";
            return View("Index", modelpaging);

        }
        [HttpGet]
        public IActionResult AddBook()
        {
            /// meqdardehi be drop down list ha


            AddEditBookViewModel model = new AddEditBookViewModel();

            model.BookGroups = _context.BookGroups.Select(bg => new SelectListItem
            {
                Text = bg.BookGroupName,
                // BookGroupId az noe int gereftitm va value az noe stringe braye hamin az tostring() estefade kardim
                Value = bg.BookGroupId.ToString()
            }).ToList();
            model.Authors = _context.Authors.Select(a => new SelectListItem
            {
                Text = a.AuthorName,
                Value = a.AuthorId.ToString()


            }).ToList();
            return PartialView("_AddEditBook", model);
        }

        [HttpGet]
        public IActionResult EditBook(int id)
        {
            AddEditBookViewModel model = new AddEditBookViewModel();

            model.BookGroups = _context.BookGroups.Select(bg => new SelectListItem
            {
                Text = bg.BookGroupName,
                // BookGroupId az noe int gereftitm va value az noe stringe braye hamin az tostring() estefade kardim
                Value = bg.BookGroupId.ToString()
            }).ToList();
            model.Authors = _context.Authors.Select(a => new SelectListItem
            {
                Text = a.AuthorName,
                Value = a.AuthorId.ToString()


            }).ToList();

            if (id != 0)
            {
                using (var db = _iServiceProvider.GetRequiredService<ApplicationDbContext>())
                {
                    Book book = _context.Books.Where(b => b.BookId == id).SingleOrDefault();
                    if (book != null)
                    {
                        model.BookId = book.BookId;
                        model.BookName = book.BookName;
                        model.BookDescription = book.BookDescription;
                        model.BookPageCount = book.BookPageCount;
                        model.AuthorId = book.AuthorID;
                        model.BookGroupId = book.BookgroupID;
                        model.Price = book.Price;
                        model.BookImage = book.BookImage;
                    }
                }
            }

            return PartialView("_AddEditBook", model);
        }

        [HttpPost]
        // [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddEditBook(AddEditBookViewModel model, int bookId,
            IEnumerable<IFormFile> files, string ImageName)
        {

            if (ModelState.IsValid)
            {
                ///upload iamge//////
                var uploads = Path.Combine(_appEnvironment.WebRootPath, "upload\\normalImage\\");
                foreach (var file in files)
                {
                    if (file != null && file.Length > 0)
                    {
                        var filename = Guid.NewGuid().ToString().Replace("-", "") + Path.GetExtension(file.FileName);

                        using (var filestream = new FileStream(Path.Combine(uploads, filename), FileMode.Create))
                        {
                            await file.CopyToAsync(filestream);
                            model.BookImage = filename;
                        }

                        ///ایجاد تصاویر بند انگشتی یا تصاویر کوچک ///ایجاد تصاویر بند انگشتی یا تصاویر کوچک
                        InsertShowImage.ImageResizer img = new InsertShowImage.ImageResizer();
                        img.Resize(uploads + filename,
                            _appEnvironment.WebRootPath + "\\upload\\thumbnailImage\\" + filename);
                    }
                }
                ///upload image///

                if (bookId == 0)
                {
                    if (model.BookImage == null)
                    {
                        // اگر تصویر انتخاب نشده بود.
                        model.BookImage = "defaultpic.png";
                    }

                    //afzodan

library10/Areas/Admin/Views/Book/BookDetails.cshtml
@model library10.Models.ViewModels.MultiModels

@{
    ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, library10
@using Microsoft.AspNetCore.Identity
@using library10.Models

@inject SignInManager<ApplicationUser> signInManager

@inject UserManager<ApplicationUser> userManager


<div id="main-div" class="container">

    <div id="right-panel" class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
        <!--start right-panel-->
        <!--سبد-->
        @if (signInManager.IsSignedIn(User))
        {
            <div id="rightpanel-sabad">
                @Html.Partial("_SabadeAmanat")
            </div>

        }


        <!--سبد-->
        <div id="Lastnews" class="div-style">
            <!--start lasnews-->
            @Html.Partial("_LastnewsPartial", Model.LastNews)

        </div><!--end lastnews-->
        <div id="Names" class="div-style">
            <!--start names-->
            @Html.Partial("_SabtenamePartial", Model.Userlisted)

        </div><!--end names-->

    </div><!--end right-panel-->

    <div id="bookdetails" class="col-lg-8 col-md-8 col-sm-12 col-xs-12">


        @foreach (var item in Model.bookDetail)
        {
            <span style="font-size: 19px">عنوان کتاب : <span>@item.BookName</span></span>
            <hr class="hr" />
            <div class="col-md-12">
                <div class="col-md-7">
                    <div>
                        <span style="font-size: 17px;">@Html.DisplayNameFor(model => item.BookGroupName) :<span>@item.BookGroupName</span></span>
                    </div>
                    <br />
                    <div>
                        <span style="font-size: 17px;">@Html.DisplayNameFor(model => item.AuthorName) :<span>@item.AuthorName</span></span>
                    </div>
                    <br />
                    <div>
                        <span style="font-size: 17px;">@Html.DisplayNameFor(model => item.BookPageCount) :<span>@item.BookPageCount</span></span>
                    </div>
                    <br />
                    <div>
                        <span style="font-size: 17px;">@Html.DisplayNameFor(model => item.BookStock) :<span>@item.BookStock</span></span>
                    </div>
                    <br />
                    <div>
                        <span style="font-size: 17px;">@Html.DisplayNameFor(model => item.Price) :<span>@item.Price</span></span>
                    </div>
                    <br />
                    <div>
                        <span style="font-size: 17px;">@Html.DisplayNameFor(model => item.BookViews) :<span>@item.BookViews</span></span>
                    </div>

                    <br />


                    <div class="col-md-12">


                        @* -------------------------------- *@
                        @if (signInManager.IsSignedIn(User))
                        {
                                <a id="btnbookborrow" class="btn btn-success">به امانت بردن</a>

                        }
                        

                        @* ------------------------------------- *@
                        
                        

                        <span id="spnbookid" class="col-md-offset-1"></span>

                        <a id="btnlike" class="btn btn-success glyphicon glyphicon-thumbs-up"></a>
                        <span id="likcounter">@item.BookLikeCount</span>
                        <a id="btndislike" class="btn btn-danger glyphicon glyphicon-thumbs-down"></a>

                        <span class="hidden" id="bId">@item.BookId</span>
                    </div>

                </div>
                <div class="col-md-5">
                    <div>
                        <span><img src="@ViewBag.imagepath@item.BookImage" class="thumbnail" style="width: 290px; height: 280px;" /></span>
                    </div>
                </div>

                <div class="col-md-12" style="height: 1px; width: 100%; background-color: gray; margin-top: 15px;">

                </div>
                <div class="col-md-12">
                    <span style="font-size: 17px; font-weight: 600; margin-bottom: 10px;">
                        @Html.DisplayNameFor(model => item.BookDescription)
                    </span>

                    <div>
                        @Html.Raw(item.BookDescription)
                    </div>
                </div>
            </div>
                    }

    </div>
</div>

@section Scripts{

    <script>

        $('#btnlike').on("click", function () {

            var post_data = $('#bId').text();

            $.ajax({
                type: 'POST',
                url: '@Url.Action("Like","Book")',

                data: { 'bId': post_data },

                success: function(msg) {
                    if (msg.status === 'success') {
                        alert(msg.message);
                        $('#likcounter').text(msg.result)
                    }
                }

            });
        });
//-------------------------------------------------------------------------------------

        $('#btndislike').on("click", function () {

            var post_data = $('#bId').text();

            $.ajax({
                type: 'POST',
                url: '@Url.Action("DisLike", "Book")',

                data: { 'bId': post_data },

                success: function(msg) {
                    if (msg.status === 'success') {
                        alert(msg.message);
                        $('#likcounter').text(msg.result)
                    }
                }

            });
        });
//-------------------------------------------------------------------------------------
        $('#btnbookborrow').on("click", function () {

            //post_data = $('#bId').text();

            $.ajax({
                type: 'POST',
                url: '@Url.Action("Borrow", "Book")',

                data: { 'Id': $('#bId').text() },

                success: function(msg) {
                    if (msg.status === 'success') {
                        alert(msg.message);
                        $('#requestcount').text(msg.sabadcount);
                    } else {
                        alert(msg.message);
                    
                    }
                }

            });
        });




    </script>
}

library10/Areas/Admin/Views/Book/Index.cshtml
@model ReflectionIT.Mvc.Paging.PagingList<library10.Models.ViewModels.BookListViewModel>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, library10
@using System.Diagnostics.Tracing
@using library10.PublicModel
@using ReflectionIT.Mvc.Paging


@{
    ViewData["Title"] = "لیست کتابها";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    @Html.Partial("_AdminPanel")
</div>
<div class="col-md-9">

    <div class="panel panel-primary">



        <div class="panel-heading">

            <div class="col-md-3" style="font-size: 17px;">لیست نویسندگان</div>
            <div>
                <form asp-controller="Book" asp-action="SearchBook">
                    <div class="input-group">
                        <div class="col-md-4">
                            <input type="text" id="bookSearch" name="bookSearch" class="form-control" placeholder="جستجو در کتابها.." />
                        </div>
                        <div class="col-md-4">
                            <input type="text" id="authorSearch" name="authorSearch" class="form-control" placeholder="جستجو در نویسندگان.." />
                        </div>
                        <div class="col-md-4">
                            <input type="text" id="bookgroupSearch" name="bookgroupSearch" class="form-control" placeholder="جستجو در گروه بندی.." />
                        </div>
                        <div class="input-group-btn">
                            <button class="btn btn-success pull-right">جستجو!</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="panel-body">
            <div class="btn btn-group marginbootn ">


                <a class="btn btn-primary" id="ShowBook" data-toggle="modal" asp-action="AddBook"
                   data-target="#modal-action-book">
                    <i class="glyphicon glyphicon-plus"></i>
                    افزودن کتاب جدید

                </a>

            </div>

            <table class="table table-bordered table-striped table-condensed" style="border:1px solid black">

                <thead>
                    <tr>
                        <th style="font-weight: 600">ردیف</th>
                        <th class="text-center">@Html.DisplayNameFor(model => model.BookName) </th>
                        <th class="text-center">@Html.DisplayNameFor(model => model.BookPageCount) </th>
                        <th class="text-center">@Html.DisplayNameFor(model => model.Price) </th>
                        <th class="text-center">@Html.DisplayNameFor(model => model.AuthorName) </th>
                        <th class="text-center">@Html.DisplayNameFor(model => model.BookGroupName) </th>
                        <th class="text-center">@Html.DisplayNameFor(model => model.BookImage) </th>


                        <th class="text-center">عملیات</th>

                    </tr>
                </thead>
                <tbody>
                @{
                    int Counter = 1;
                    foreach (var item in Model)
                    {

                        <tr>
                            <td class="text-center">@(Counter++)</td>
                            <td class="text-center">@item.BookName</td>
                            <td class="text-center">@item.BookPageCount</td>
                            <td class="text-center">@item.Price</td>
                            <td class="text-center">@item.AuthorName</td>
                            <td class="text-center">@item.BookGroupName</td>

                            <td class="text-center">
                                <img src="@ViewBag.Rootpath@item.BookImage" style="width: 80px; height: 80px;" class="thumbnail">
                            </td>
                            <td class="text-center">
                                <a asp-action="EditBook" asp-route-id="@item.BookId" class="btn btn-info" id="ShowEditBook" data-toggle="modal"
                                   data-target="#modal-action-book">
                                    <i class="glyphicon glyphicon-pencil"></i>
                                    ویرایش کتاب
                                </a>

                                <a asp-action="DeleteBook" asp-route-id="@item.BookId" class="btn btn-danger" id="ShowDeleteBook" data-toggle="modal"
                                   data-target="#modal-action-book-delete">
                                    <i class="glyphicon glyphicon-trash"></i>
                                    حذف کتاب
                                </a>

                            </td>
                        </tr>
                    }
                }
                </tbody>
            </table>
            <nav class="text-center">
                @await this.Component.InvokeAsync("Pager",new {PagingList=this.Model })
            </nav>
        </div>
    </div>

</div>

@Html.Partial("_Modal", new BootstrapModel { ID = "modal-action-book", Size = ModalSize.Large })
@Html.Partial("_Modal", new BootstrapModel { ID = "modal-action-book-delete", Size = ModalSize.Medium })


@section Scripts{

    <script src="~/js/ModalJs/Book-index.js"></script>
    <script src="~/js/ModalJs/Modal-book-delete.js"></script>
    <script src="~/js/ckeditor/ckeditor.js"></script>
    <script src="~/js/AdminPanelScript.js"></script>

    <script>
        $(document).on('click',
            '#submitdata',
            function(evt) {

                evt.preventDefault();


                var data = new FormData();

                //دریافت مقادیر فایل آپلودی
                var fileupload = $("#files").get(0);
                var files = fileupload.files;

                for (var i = 0; i < files.length; i++) {
                    data.append('files', files[i]);
                }

                //دریافت مقادیر موجود
                $('input,select').each(function(x,y) {

                    data.append($(y).attr('name'), $(y).val());

                });


                //دریافت مقادیر ادیتور

                var editorval = CKEDITOR.instances['BookDescription'].getData();

                data.append('BookDescription', editorval);

                ////ارسال به سمت سرور با ایجکس

                $.ajax({
                    type: "post",
                    url: '@Url.Action("AddEditBook","Book",new{area ="Admin"})',
                    contentType: false,
                    processData: false,
                    data: data

                }).done(function(res) {
                    //منظور از دون  وقتی اطلاعات به سمت سرور رفت و جواب از سرور آمد
                    if (res.status === "success") {
                        alert(res.message);

                        window.location.href = '@Url.Action("Index","Book")';
                    } else {

                        $.each(res.error, function(a, b) {
                            alert(b);
                        });

                    }
                }).fail(function(xhr, b, error) {
                    //منظور از فیل وقتی اطلاعات به سمت سرور نرفت و در همان کامپیوتر کلاینت یا در بدو ورود به سرور خطاداد

                    alert(error);

                });


            });

    </script>
}

library10/Areas/Admin/Views/Book/_AddEditBook.cshtml
@model library10.Models.ViewModels.AddEditBookViewModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, library10
@using library10.PublicModel

<form method="post" enctype="multipart/form-data">

    @* Header *@
    @if (Model.AuthorId == 0)

    {
        @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "افزودن کتاب" })

    }

    else
    {
        @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading = "ویرایش کتاب" })

    }
    @Html.AntiForgeryToken();

    @* body *@
    <div class="modal-body form-horizontal">
        <div class="row">
            <div class="form-group">
                <label asp-for="BookName" class="col-lg-2 col-sm-2 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="BookName" class="form-control" />
                </div>
            </div>

            <div class="form-group">
                <label asp-for="BookDescription" class="col-lg-2 col-sm-2 control-label"></label>
                <div class="col-lg-9">
                    <textarea asp-for="BookDescription" class="form-control" id="BookDescription" name="BookDescription"></textarea>

                </div>

                <script type="text/javascript">
                    CKEDITOR.replace('BookDescription');

                </script>
            </div>

            <div class="form-group">
                <label asp-for="BookGroupId" class="col-lg-2 col-sm-2 control-label"></label>
                <div class="col-lg-6">
                    <select asp-for="BookGroupId" asp-items="@Model.BookGroups" class="form-control"></select>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="AuthorId" class="col-lg-2 col-sm-2 control-label"></label>
                <div class="col-lg-6">
                    <select asp-for="AuthorId" asp-items="@Model.Authors" class="form-control"></select>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="BookPageCount" class="col-lg-2 col-sm-2 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="BookPageCount" class="form-control" />
                </div>
            </div>
            
            
            <div class="form-group">
                <label asp-for="Price" class="col-lg-2 col-sm-2 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="Price" class="form-control" />
                </div>
            </div>
            
            <div class="form-group">
                <label asp-for="BookImage" class="col-lg-2 col-sm-2 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="BookImage" type="file" id="files" name="files" multiple />
                </div>
                @if (Model.BookId != 0)
                {
                    <input type="hidden" name="ImageName" value="@Model.BookImage" />
                }
            </div>


            <div class="form-group hidden">
                <label asp-for="BookId" class="col-lg-2 col-sm-2 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="BookId" class="form-control" />
                </div>
            </div>

            @*<input type="hidden" name="redirecturl" value="@Url.Action("Index","Book")" />*@
            @*بخاطر استفاده از جی کوئری برای ارسال فرم دیگر نیازی به این دستور نیست  *@
        </div>


    </div>

    @* Footer *@
    @if (Model.AuthorId == 0)
    {

        @*@await Html.PartialAsync("_ModalFooter", new ModalFooter { SubmitButtonText = "افزودن کتاب" })*@
        <div class="modal-footer">
            <button class="btn btn-default" type="button" data-dismiss="modal">برگشت</button>

            <input type="button" id="submitdata" class="btn btn-success" value="افزودن کتاب" />

        </div>
    }
    else
    {
        <div class="modal-footer">
            <button class="btn btn-default" type="button" data-dismiss="modal">برگشت</button>

            <input type="button" id="submitdata" class="btn btn-info" value="ویرایش کتاب"/>
        </div>
    }

</form>